<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Tedd.FIC/Tedd.FIC.csproj" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SkiaSharp" Version="4.151.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.151.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.151.2" />
  </ItemGroup>
</Project>
